### ISSUE TITLE
Error: .inputSourceMap must be a boolean, object, or undefined

### ISSUE THREAD

**Issue by 0x30** [alloc/vite-plugin-legacy#2]
https://github.com/0x30/vite-plugin-legacy/commit/fadcd2e2d4a44d1025c0a52be8c0acca4ed87c1a#

and

https://github.com/0x30/vite-plugin-legacy/commit/efe0912424b248a76677eaf34a96445fdb5f08ba

**Comment by aleclarson** [comment]
Thx, published under v0.1.4

**Comment by 0x30** [comment]
Hello, 

maybe we should use configuration files such as browserlistrc and babel.config.js as much as possible, and don't re-define these configurations by passing them.  

In addition, I don’t know much about polyfill.io... But I can’t accept it. Import a file into my project through external links... At least it should be within my control...

**Comment by aleclarson** [comment]
I would prefer if you opened a new issue for each concern.

> maybe we should use configuration files such as browserlistrc and babel.config.js as much as possible, and don't re-define these configurations by passing them.

We already use browserslist config by default, since that's how `@babel/preset-env` works. If it's not working, let me know.

If you want `babel.config.js` to be applied, you can add `@rollup/plugin-babel` to the `rollupInputOptions.plugins` array in your Vite config. Then your Babel config will be applied to both modern and legacy bundles.

```js
import { getBabelOutputPlugin } from "@rollup/plugin-babel";
import path from "path";

export default {
  rollupInputOptions: {
    plugins: [
      getBabelOutputPlugin({
        configFile: path.resolve(__dirname, "babel.config.js"),
      }),
    ],
  },
};
```

> In addition, I don’t know much about polyfill.io... But I can’t accept it. Import a file into my project through external links... At least it should be within my control...

You can set `corejs: true` to disable Polyfill.io imports. 

Note: The `polyfills` option will always add a Polyfill.io import.
